package ru.itmo.kursach_back.service;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;
import ru.itmo.kursach_back.dto.request.GenerateDesignRequestDto;
import ru.itmo.kursach_back.dto.response.DesignResponseDto;
import ru.itmo.kursach_back.entity.Design;
import ru.itmo.kursach_back.entity.User;
import ru.itmo.kursach_back.repository.DesignRepository;
import ru.itmo.kursach_back.service.ai.AIService;
import ru.itmo.kursach_back.service.ai.AIServiceFactory;

import java.io.IOException;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class DesignService {

    private final DesignRepository designRepository;
    private final AuthService authService;
    private final ImageService imageService;
    private final AIServiceFactory aiServiceFactory;

    @Transactional
    public DesignResponseDto generateDesign(GenerateDesignRequestDto request) {
        User currentUser = authService.getCurrentUser();

        Design design = new Design();
        design.setOwnerId(currentUser.getUserId());
        design.setOriginalPrompt(request.getPrompt());
        design.setModelId(request.getAiModelId());
        design.setIsAiGenerated(true);
        design.setCreatedAt(LocalDateTime.now());
        design.setModifiedAt(LocalDateTime.now());

        design = designRepository.save(design);

        try {

            AIService aiService = aiServiceFactory.getService(request.getAiModelId());

            java.util.Map<String, Object> params = new java.util.HashMap<>();
            params.put("size", "1024x1024");
            params.put("quality", "standard");

            String fullPrompt = request.getPrompt();
            if (request.getText() != null && !request.getText().isEmpty()) {
                fullPrompt += " with text: \"" + request.getText() + "\"";
            }
            if (request.getTheme() != null) {
                fullPrompt += " in " + request.getTheme().toLowerCase() + " style";
            }

            byte[] imageBytes = aiService.generateImage(fullPrompt, params);

            org.springframework.web.multipart.MultipartFile mockFile = createMultipartFile(imageBytes, "generated-" + design.getDesignId() + ".png");
            ru.itmo.kursach_back.entity.ImageData savedImage = imageService.saveImage(
                mockFile,
                currentUser.getUserId(),
                "AI Generated: " + request.getPrompt().substring(0, Math.min(50, request.getPrompt().length())),
                "Generated by " + aiService.getServiceName()
            );

            design.setImageId(savedImage.getImgdId());
            design.setModifiedAt(LocalDateTime.now());
            design = designRepository.save(design);

            DesignResponseDto response = convertToDto(design);
            response.setStatus("COMPLETED");
            response.setPrompt(request.getPrompt());
            response.setText(request.getText());
            response.setTheme(request.getTheme());
            response.setAiModelId(request.getAiModelId());

            return response;

        } catch (Exception e) {

            DesignResponseDto response = convertToDto(design);
            response.setStatus("FAILED");
            response.setPrompt(request.getPrompt());
            response.setText(request.getText());
            response.setTheme(request.getTheme());
            response.setAiModelId(request.getAiModelId());
            response.setImageUrl(null);

            throw new RuntimeException("Failed to generate design: " + e.getMessage(), e);
        }
    }

    private MultipartFile createMultipartFile(byte[] content, String filename) {
        return new MultipartFile() {
            @Override
            public String getName() { return "file"; }

            @Override
            public String getOriginalFilename() { return filename; }

            @Override
            public String getContentType() { return "image/png"; }

            @Override
            public boolean isEmpty() { return content.length == 0; }

            @Override
            public long getSize() { return content.length; }

            @Override
            public byte[] getBytes() { return content; }

            @Override
            public java.io.InputStream getInputStream() {
                return new java.io.ByteArrayInputStream(content);
            }

            @Override
            public void transferTo(java.io.File dest) throws java.io.IOException {
                java.nio.file.Files.write(dest.toPath(), content);
            }
        };
    }

        public List<DesignResponseDto> getMyDesigns() {
        User currentUser = authService.getCurrentUser();
        List<Design> designs = designRepository.findByOwnerIdOrderByCreatedAtDesc(currentUser.getUserId());
        return designs.stream().map(this::convertToDto).collect(Collectors.toList());
    }

        public DesignResponseDto getDesignById(Integer designId) {
        Design design = designRepository.findById(designId)
                .orElseThrow(() -> new RuntimeException("Design not found"));

        User currentUser = authService.getCurrentUser();
        if (currentUser != null && !design.getOwnerId().equals(currentUser.getUserId())) {
            throw new RuntimeException("Access denied");
        }

        return convertToDto(design);
    }

        @Transactional
    public void deleteDesign(Integer designId) {
        User currentUser = authService.getCurrentUser();
        Design design = designRepository.findById(designId)
                .orElseThrow(() -> new RuntimeException("Design not found"));

        if (!design.getOwnerId().equals(currentUser.getUserId())) {
            throw new RuntimeException("Access denied");
        }

        designRepository.delete(design);
    }

        public List<DesignResponseDto> getGenerationHistory() {
        User currentUser = authService.getCurrentUser();
        List<Design> designs = designRepository.findByOwnerIdOrderByCreatedAtDesc(currentUser.getUserId());
        return designs.stream().map(this::convertToDto).collect(Collectors.toList());
    }

        public byte[] getDesignImage(Integer designId) throws IOException {
        Design design = designRepository.findById(designId)
                .orElseThrow(() -> new RuntimeException("Design not found"));

        if (design.getImageId() == null) {
            return null; // No image associated with this design yet
        }

        return imageService.getImageFile(design.getImageId());
    }

        public List<DesignResponseDto> getPublicDesigns() {
        List<Design> designs = designRepository.findByIsPublicTrueOrderByCreatedAtDesc();
        return designs.stream().map(this::convertToDtoWithOwner).collect(Collectors.toList());
    }

        public List<Design> getAllDesignsForModerator() {
        return designRepository.findAll();
    }

    public java.util.Optional<Design> findDesignById(Integer designId) {
        return designRepository.findById(designId);
    }

        @Transactional
    public DesignResponseDto updateDesignVisibility(Integer designId, Boolean isPublic) {
        User currentUser = authService.getCurrentUser();
        Design design = designRepository.findById(designId)
                .orElseThrow(() -> new RuntimeException("Design not found"));

        if (!design.getOwnerId().equals(currentUser.getUserId())) {
            throw new RuntimeException("Access denied");
        }

        design.setIsPublic(isPublic);
        design.setModifiedAt(LocalDateTime.now());
        design = designRepository.save(design);

        return convertToDto(design);
    }

        @Transactional
    public Design updateDesignVisibilityByModerator(Integer designId, Boolean isPublic) {
        Design design = designRepository.findById(designId)
                .orElseThrow(() -> new RuntimeException("Design not found"));

        design.setIsPublic(isPublic);
        design.setModifiedAt(LocalDateTime.now());
        return designRepository.save(design);
    }

    private DesignResponseDto convertToDto(Design design) {
        DesignResponseDto dto = new DesignResponseDto();
        dto.setDesignId(design.getDesignId());

        if (design.getImageId() != null) {
            dto.setImageUrl("/api/designs/" + design.getDesignId() + "/image");
        } else {
            dto.setImageUrl(null); // Image not yet generated
        }

        dto.setPrompt(design.getOriginalPrompt());
        dto.setStatus("COMPLETED"); // Default status, can be enhanced with actual status tracking
        dto.setUserId(design.getOwnerId());
        dto.setAiModelId(design.getModelId());
        dto.setCreatedAt(design.getCreatedAt() != null ? design.getCreatedAt().toString() : null);

        return dto;
    }

    private DesignResponseDto convertToDtoWithOwner(Design design) {
        DesignResponseDto dto = convertToDto(design);

        if (design.getOwner() != null) {
            dto.setOwnerUsername(design.getOwner().getUsername());
        }

        return dto;
    }

    public List<Map<String, Object>> getPopularDesigns(Integer limit) {
        return designRepository.getPopularDesigns(limit != null ? limit : 10);
    }

    public Boolean isDesignPopular(Integer designId) {
        return designRepository.isPopularDesign(designId);
    }

    public Map<String, Object> getDesignStatistics(Integer designId) {
        return designRepository.getDesignStats(designId);
    }
}
